version: "3.7"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  seatplus-code:
    driver: local
  mariadb:
    driver: local

    #networks:
      #backend:

services:

  ### MariaDB ##############################################
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "mariadb:/var/lib/mysql"
    networks:
      - backend

  ### Redis ################################################
  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - backend
    
  ### nginx ################################################
  nginx:
    image: seatplus/nginx:latest
    depends_on:
      - seat-plus
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - "seatplus-code:/var/www"
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - backend
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  ### seat-plus ################################################
  seat-plus:
    image: seatplus/app:latest
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seatplus-code:/var/www"
      # Remove the comment below to enable SeAT plus logs to disk.
      #- ./logs:/var/www/storage/logs
    depends_on:
      - mariadb
      - redis
      - selenium
    networks:
      - backend

  ### worker ################################################
  worker:
    image: seatplus/worker:latest
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seatplus-code:/var/www"
    depends_on:
      - seat-plus # for the seatplus-code volume
      - mariadb
      - redis
    networks:
      - backend

  ### cron ################################################
  cron:
    image: seatplus/worker:latest
    restart: always
    environment:
      CONTAINER_ROLE: cron
      DB_HOST: mariadb
        REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seatplus-code:/var/www"
    depends_on:
      - seat-plus
      - mariadb
      - redis
    networks:
      - backend

  ### Dusk ####################################
  selenium:
    image: 'selenium/standalone-chrome'
    volumes:
      - '/dev/shm:/dev/shm'



